title: Riftlink
theme: riftlink
baseURL: https://www.riftlink.gg
languageCode: es-es
defaultContentLanguage: es
metaDataFormat: yaml

module:
  mounts:
    - source: node_modules/bootstrap/scss
      target: assets/scss/bootstrap
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js
      target: assets/js/bootstrap.min.js
